#include "C.h"

const float C::PLAYER_VELOCITY_NORMAL_X = 180;
const float C::PLAYER_VELOCITY_NORMAL_Y = 180;
const float C::PLAYER_NORMAL_BULLET_VELOCITY_NORMAL_Y = 600;
const float C::PLAYER_NORMAL_BULLET_INTERVAL = 0.15f;
const float C::NORMAL_ENEMY_VELOCITY_NORMAL = 120;
